---
language: ruby

rvm:
  - 2.2.3

sudo: required

dist: trusty

env:
  - INVENTORY=rails_1 PLAYBOOK=provision_with_docker TEST=true RSPEC_TEST_NAME=provision_ubuntu_spec ANSIBLE_VERSION=1.9.4
  - INVENTORY=rails_1 PLAYBOOK=provision_with_docker TEST=true RSPEC_TEST_NAME=provision_ubuntu_spec ANSIBLE_VERSION=2.0.1.0

services:
  - docker

before_install:
  - sudo pip install ansible==${ANSIBLE_VERSION} docker-py pyopenssl ndg-httpsclient pyasn1

install:
  - bundle install --jobs=3 --retry=3
  - ./scripts/galaxy_install.sh
  - ./scripts/update_insecure_keys_permissions.sh

script:
  - "./scripts/ansible_syntax_check.sh $INVENTORY $PLAYBOOK"

  - "./scripts/ansible_docker_run.sh -vv"

  - >
    ./scripts/ansible_docker_run.sh -vv
    | grep -q 'changed=0.*unreachable=0.*failed=0.*'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && cat /tmp/ansible.log && exit 1)

  - "rspec ./spec/${INVENTORY}/${RSPEC_TEST_NAME}.rb"
