---
development_ubuntu_packages:
  - software-properties-common
  - python-software-properties
  - curl
  - build-essential
  - libpq-dev
  - libssl-dev
  - libreadline-dev
  - zlib1g-dev
  - libffi-dev
  - libncurses5-dev
  - libyaml-dev
  - libxml2
  - libxml2-dev
  - libxslt1-dev
  - libsqlite3-dev
  - git
  - autoconf
  - apt-transport-https
