---
- name: update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install system packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: development_ubuntu_packages
